### ISSUE TITLE
Broken link for How2Sign dataset

### ISSUE THREAD

**Issue by huberemanuel** [sign-language-processing/sign-language-processing.github.io#11]
The link presented on README.md for How2Sign isn't working anymore. The link presented on the dataset page is [this](https://github.com/srvk/how2-dataset).

**Comment by AmitMY** [comment]
Thanks! Resolved in https://github.com/sign-language-processing/sign-language-processing.github.io/commit/bbff49a84fbb90fc6c9797a25258a580ced295b0
