### ISSUE TITLE
Web app display is incomplete

### ISSUE THREAD

**Issue by arnaudnjita** [sign-language-processing/sign-language-processing.github.io#20]
Hi @AmitMY I cloned the project to my local machine and tried running it but this is what I get after starting the server and opening it in the web browser.
**Env. specs**
Windows 11 | Python 3.11.0 | node v16.17 | Chocolatey v1.3.0 | Pandoc 3.1 | GNU Make 4.3

**Web**
![image](https://user-images.githubusercontent.com/50627574/221564826-691b7cba-c0b9-4a5e-afad-907cca17a38c.png)

**CMD**
![image](https://user-images.githubusercontent.com/50627574/221565678-49aed729-4e88-46c1-aaca-3b24edef5e0f.png)

Please any help or idea about why it's running partially? thanks

**Comment by AmitMY** [comment]
Did you run `make` ? (or `watch make`)

**Comment by arnaudnjita** [comment]
Well when I run make this is what I get
![image](https://user-images.githubusercontent.com/50627574/221569421-325ca39b-59de-4d33-a77a-4ba190a33f87.png)

**Comment by arnaudnjita** [comment]
So after deleting the `/dst` folder and running `make` again I get this

![image](https://user-images.githubusercontent.com/50627574/221589863-e6147163-d52e-4b16-b22f-a24a2a42e8fb.png)

I don't really get why it says the syntax of the command is incorrect

**Comment by AmitMY** [comment]
You seem to be using windows command line. 
Please use `bash` instead. 

I recommend git bash:
https://github.com/git-for-windows/git/releases/download/v2.39.2.windows.1/Git-2.39.2-32-bit.exe

But you can also just use `Bash on Ubuntu on Windows`

**Comment by arnaudnjita** [comment]
**Thanks @AmitMY by using git bash it now runs well, so there has been progress so far.**

![image](https://user-images.githubusercontent.com/50627574/221660138-374f7d4d-2bfe-4401-9ba0-ed2dfead091b.png)

**But for some reason it's displaying this "HTTP Error 404: Not Found" as you can see in the skeleton display section even for the web app that is already deployed an available online(Got any clues for this?)**

![image](https://user-images.githubusercontent.com/50627574/221723972-89af1b27-fcd4-43f7-be5e-96f057aeea1e.png)

![image](https://user-images.githubusercontent.com/50627574/221724194-9fdf3cec-fc20-43a6-8aff-7ed510367daa.png)

**Comment by AmitMY** [comment]
Thanks for letting me know.
One of the university servers is down.
You can still do `german->Switzerland` translation (https://sign.mt/?sil=ch&spl=de&text=hallo) as it uses a different server.
It should return to normal operation soon-ish (by tomorrow)
