### ISSUE TITLE
Source code/repo for 'https://sign.mt/' not available

### ISSUE THREAD

**Issue by arnaudnjita** [sign-language-processing/sign-language-processing.github.io#21]
Hi @AmitMY I noticed that this project [https://research.sign.mt/](https://research.sign.mt/) is actually just an iFrame embed of this [https://sign.mt/](https://sign.mt/) with the additional research documentation included.

So please I wish to know if the source code or actual repo for this project([https://sign.mt/](https://sign.mt/)) hosted is actually open source and available for modifications, because right now I have no possibility of customizing or making any modifications since it's just an iFrame embeded into this project [https://research.sign.mt/](https://research.sign.mt/)

![image](https://user-images.githubusercontent.com/50627574/222668239-d44720c4-6553-48d9-8401-e1c229a83d01.png)

**Comment by AmitMY** [comment]
The source for that app is available in:
https://github.com/sign/translate

**Comment by arnaudnjita** [comment]
Thank you sir
