### ISSUE TITLE
A simple question

### ISSUE THREAD

**Issue by FangSen9000** [sign-language-processing/sign-language-processing.github.io#26]
![image](https://github.com/sign-language-processing/sign-language-processing.github.io/assets/72308243/e452ca50-f2f7-4085-9a92-ab9d3bb5f361)

Was the above video achieved by following this step? Or is it some other way? @AmitMY 
pix2pix to implement the pose_sequence to pose_video is a little weird.

![image](https://github.com/sign-language-processing/sign-language-processing.github.io/assets/72308243/c189f574-68d4-4969-8720-ed749fae0ed7)

**Comment by AmitMY** [comment]
If you want the skeleton as a video file, that is implemented in the pose library https://github.com/sign-language-processing/pose using `visualize_pose -i example.pose -o example.mp4`

If you want the skeleton to be transformed to a human like video, consult the readme of https://github.com/sign-language-processing/pose-to-video
