### ISSUE TITLE
Website references list: "Sign Language Transformers" citation author shows as "---"

### ISSUE THREAD

**Issue by cleong110** [sign-language-processing/sign-language-processing.github.io#36]
https://research.sign.mt/#ref-camgoz2020sign shows as 
![image](https://github.com/sign-language-processing/sign-language-processing.github.io/assets/122366389/bd81b828-29c5-4e7c-9796-c5d8364c906b)

I checked the references.bib and it seems perfectly normal: 

https://github.com/sign-language-processing/sign-language-processing.github.io/blob/master/src/references.bib#L726-L732

Not sure what's going on

**Comment by AmitMY** [comment]
That just means "same people as above"
![image](https://github.com/sign-language-processing/sign-language-processing.github.io/assets/5757359/af0f22ae-4f5e-484a-95c5-4cce2fc6537e)
