### ISSUE TITLE
Integrate a bibtex linter

### ISSUE THREAD

**Issue by cleong110** [sign-language-processing/sign-language-processing.github.io#40]
>not an error, and can probably integrate a linter (for example https://github.com/jlibovicky/prettybib) to alert/fix these issues.
`INPROCEEDINGS` is capital, and usually is not.
volume and number are empty, so should be removed
the last `}` should be in a new line

_Originally posted by @AmitMY in https://github.com/sign-language-processing/sign-language-processing.github.io/pull/38#discussion_r1607026519_

**Comment by AmitMY** [comment]
Your thoughts on https://github.com/sign-language-processing/sign-language-processing.github.io/pull/41?

**Comment by cleong110** [comment]
Scrolled through the diff on references.bib, seems pretty good!
* mostly indentation normalization
* consistently changes from {Last, First and Last2, First2} to {First Last and First2 Last2}, I wonder about that. At least it's consistent now!
* reference.bib is much taller vertically, but you no longer have to scroll to the right for long author lists
* Have we tested whether it will fix things like: egregious `{}` or empty fields?

I say we merge it in!

**Comment by cleong110** [comment]
Oh, it successfully updated "How2Sign" with the official citation! Nice!
